// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDmP228Ds0ZYXqvwN17uIZ8RD6z4qy64',
    appId: '1:87037970878:web:d239cb833b4df3183151ef',
    messagingSenderId: '87037970878',
    projectId: 'atlas-a655a',
    authDomain: 'atlas-a655a.firebaseapp.com',
    storageBucket: 'atlas-a655a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVWyWEA-zRw3IIRlMN9ag-ZuqZqFb-Sk',
    appId: '1:87037970878:android:3cae5bf2984651873151ef',
    messagingSenderId: '87037970878',
    projectId: 'atlas-a655a',
    storageBucket: 'atlas-a655a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVOK4LkSP5kb3zI1hbPm4kBYeOBX-HUlc',
    appId: '1:87037970878:ios:7e2049114bf352bf3151ef',
    messagingSenderId: '87037970878',
    projectId: 'atlas-a655a',
    storageBucket: 'atlas-a655a.appspot.com',
    iosBundleId: 'com.example.fluttergames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVOK4LkSP5kb3zI1hbPm4kBYeOBX-HUlc',
    appId: '1:87037970878:ios:42fae0c162d60fa83151ef',
    messagingSenderId: '87037970878',
    projectId: 'atlas-a655a',
    storageBucket: 'atlas-a655a.appspot.com',
    iosBundleId: 'com.example.fluttergames.RunnerTests',
  );
}
